### ISSUE TITLE
Working with CKEditor : button 'source' is disabled

### ISSUE THREAD

**Issue by Bomere** [symfony-cmf/CreateBundle#123]
Hi, 
I have a mistake with CKEditor. It's a feature or a bad config ? 

I installed the bundle symfony-cmf and the create-bundle. 
In file 'composer.json', I added extra info to get full ckeditor version.

``` yml
"extra": {
        ...
        "ckeditor-directory": "vendor/symfony-cmf/create-bundle/Symfony/Cmf/Bundle/CreateBundle/Resources/public/vendor/ckeditor",
        "ckeditor-repository": "https://github.com/ckeditor/ckeditor-releases.git",
        "ckeditor-commit": "fe258604491af861b44b48e48c3e9a997ff7b2ad"
}
```

It's works ! The full version is in cmfcreate bundle directory ( /bundles/cmfcreate/vendor/ckeditor/ ).
But I have all buttons except the source button. I don't understand why...

![capture d ecran 2014-09-11 a 17 41 54](https://cloud.githubusercontent.com/assets/8299312/4236855/46e0aeb8-39ca-11e4-9113-ef0055e37842.png)

If someone would like to enlighten me ? 

Thank you
